# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2zxhCtGEZbkXIRJCwURfhMZ0XCCc3o2
"""

import random

#listas de categorias

Del_1_18 = list(range(1,19))
Del_19_36 = list(range(19,37))
par = list(range(2,37,2))
impar = list(range(1,37,2))
rojo= [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]
negro=[2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35]
verde=[0]
_1ra_docena=list(range(1,13))
_2da_docena= list(range(13,25))
_3ra_docena= list(range(25,37))
_1ra_columna=list(range(1,35,3))
_2da_columna=list(range(2,36,3))
_3ra_columna=list(range(3,37,3))
Del_0_36= list(range(0,37))

'''
Juego de la ruleta
con su explicacion y categorias
'''
print("---------Bienvenido al juego de la ruleta---------")
print("Reglas\nEL juego consiste en que tengas la mayor puntuacion posible de acuerdo a tu suerte\nIniciemos con lo basico:\nEL usuario tiene que elegir una categoria para poder participar, si acierta tendra un bonus depende la categoria que elija de lo contrario perdera puntos")
print("CATEGORIAS")

print("\nBONUS X2\n")
print("1-18  ", Del_1_18)
print("19-36 ", Del_19_36)
print("Par   ", par)
print("Impar ", impar)
print("Rojo  ", rojo)
print("Negro ", negro)
print("\nBONUS X3\n")
print(f"Docenas:\n1ra {_1ra_docena}\n2da {_2da_docena}\n3ra {_3ra_docena} ")
print(f"Columnas:\n1ra {_1ra_columna}\n2da {_2da_columna}\n3ra {_3ra_columna}")
print("\nBONUS X20\n")
print("0-36", Del_0_36)
print("Verde",verde)

#menus de categorias

def categorias() :
    print("Elija una categoria")
    print("1. BONUS X2")
    print("2. BONUS X3")
    print("3. BONUS X20")
    print("4. VOLVER ATRAS")
def bonus_2x():
    print("BONUS X2")
    print("1. 1-18")
    print("2. 19-36")
    print("3. Par")
    print("4. Impar")
    print("5. Rojo")
    print("6. Negro")
def bonus_3x():
    print("BONUS X3")
    print("1. Docenas")
    print("2. Columnas")
def bonus_docenas():
    print("Docenas")
    print("1. Primera Docena")
    print("2. Segunda Docena")
    print("3. Tercera Docena")
def bonus_columnas():
    print("Columnas")
    print("1. Primera Columna")
    print("2. Segunda Columna")
    print("3. Tercera Columna")
def bonus_20x():
    print("BONUS X20")
    print("1. 0-36")
    print("2. Verde(0)")

#inicio del juego
#listas, contador, y variables
contador=0
max_dinero= []
seguir_jugando="si"
nombres=[]
dinero = 20
max_puntuacion = []
#bucle para iniciar a jugar
while seguir_jugando=="si":
    seguir_jugando = input("Quieres jugar a la ruleta?  ").lower()
    if seguir_jugando != "si":
        break
    contador+=1
    dinero=20
    nombre= input("Ingrese su nombre: ")
    #If para verificar que el jugador no sea el mismo
    if nombre in nombres:
        print("Ya no puedes jugar, lo siento.")
        break
    else:
        print("Bienvenido a la ruleta", nombre)
    nombres.append(nombre)
    #bucle hasta que se acabe el dinero o si se quiere retirar
    while dinero !=0:
        print("")
        print("Saldo total : ", dinero, )

        print("")
        apuesta= int(input("Ingrese su apuesta: "))

        if dinero >= apuesta:
            resultado = random.randint(0, 36)
            categorias()
            categoria = int(input("Elija una categoria del 1 al 4: "))
            ganador = False
            multiplicador = 0
            #Eleccion de categorias y verificador de que se va a apostar
            if categoria == 4:
                print("Estuvo divertido mientras duramos")
                break
            if categoria == 1:
                bonus_2x()
                opcion = int(input("Elija una opcion del 1 al 6: "))
                multiplicador = 2
                if opcion == 1:
                    print("Apostaste del 1-18")
                    if resultado in Del_1_18:
                        print("¡Acertes!")
                        ganador= True
                elif opcion == 2:
                    print("Apostaste 19-36")
                    if resultado in Del_19_36:
                        print("¡Acertaste!")
                        ganador= True
                elif opcion == 3:
                    print("Apostaste Par")
                    if resultado in par:
                        print("¡Acertaste!")
                        ganador= True
                elif opcion == 4:
                    print("Apostaste Impar")
                    if resultado in impar:
                        print("¡Acertaste!")
                        ganador= True
                elif opcion == 5:
                    print("Apostaste Rojo")
                    if resultado in rojo:
                        print("¡Acertaste!")
                        ganador= True
                elif opcion == 6:
                    print("Apostaste Negro")
                    if resultado in negro:
                        print("¡Acertaste!")
                        ganador= True

                else:
                    print("Perdiste.")
                    dinero -= apuesta
            elif categoria == 2:
                bonus_3x()
                multiplicador= 3
                opcion = int(input("Elija una opcion del 1 al 2: "))
                if opcion == 1:
                    print("Apostaste Docenas")
                    bonus_docenas()
                    opcion = int(input("Elija una opcion del 1 al 3: "))
                    if opcion == 1:
                        print("Apostaste Primera Docena")
                        if resultado in _1ra_docena:
                            print("¡Acertaste!")
                            ganador= True
                    elif opcion == 2:
                        print("Apostaste Segunda Docena")
                        if resultado in _2da_docena:
                            print("¡Acertaste!")
                            ganador= True
                    elif opcion == 3:
                        print("Apostaste Tercera Docena")
                        if resultado in _3ra_docena:
                            print("¡Acertaste!")
                            ganador= True
                elif opcion == 2:
                    print("Apostaste Columnas")
                    bonus_columnas()
                    opcion = int(input("Elija una opcion del 1 al 3: "))
                    if opcion == 1:
                        print("Apostaste Primera Columna")
                        if resultado in _1ra_columna:
                            print("¡Acertaste!")
                            ganador= True
                    elif opcion == 2:
                        print("Apostaste Segunda Columna")
                        if resultado in _2da_columna:
                            print("¡Acertaste!")
                            ganador= True
                    elif opcion == 3:
                        print("Apostaste Tercera Columna")
                        if resultado in _3ra_columna:
                            print("¡Acertaste!")
                            ganador= True

            elif categoria == 3:
                bonus_20x()
                multiplicador = 20
                opcion = int(input("Elija una opcion del 1 al 2: "))
                if opcion == 1:
                    numero= int(input("Ingrese un numero del 0 al 36: "))
                    if resultado == numero:
                        print("¡Acertaste!")
                        ganador= True
                elif opcion == 2:
                    print("Apostaste verde")
                    if resultado in verde:
                        print("¡Acertaste!")
                        ganador= True

            else:
                print("Opcion no valida\nPorfavor ingrese un numero asignado")
            # Multiplicacio de ganancia o resta si esque perdio la apuesta
            if ganador:
                ganancia = apuesta * (multiplicador - 1)
                dinero += ganancia
                print(f"¡Ganaste! BONUS x{multiplicador}")
                print(f"Ganancia: +{ganancia}\n")
            else:
                dinero -= apuesta
                print("Perdiste.")
                print(f"Pérdida: -{apuesta}\n")
        else:
            print("No tienes saldo sufiente")

        #listas de las categorias

        print('--------LISTA DE CATEGORIAS GANADORAS--------')
        print("NUMERO: ",  resultado)
        if resultado in Del_1_18:
            print("SECCION 1-18")
        if resultado in Del_19_36:
            print("SECCION 19-36")
        if resultado in par:
            print("NUMERO  PAR")
        if resultado in impar:
            print("NUMERO  IMPAR")
        if resultado in rojo:
            print("COLOR   ROJO")
        if resultado in negro:
            print("COLOR   NEGRO")
        if resultado in verde:
            print("COLOR   VERDE")
        if resultado in _1ra_docena:
            print("PRIMERA DOCENA")
        if resultado in _2da_docena:
            print("SEGUNDA DOCENA")
        if resultado in _3ra_docena:
            print("TERCERA DOCENA")
        if resultado in _1ra_columna:
            print("PRIMERA COLUMNA")
        if resultado in _2da_columna:
            print("SEGUNDA COLUMNA")
        if resultado in _3ra_columna:
            print("TERCERA COLUMNA")
        pregunta= input("Quieres seguir jugando?: ")
        if pregunta == "no":
            break

# maxima putuacion
        max_dinero.append(dinero)
        max(max_dinero)
    max_puntuacion.append(max(max_dinero))
print("-------TOP GLOBALES-------")

if len(max_puntuacion)!=0:
    for i in range(contador):
        print(f"{i+1}. {nombres[max_puntuacion.index(max(max_puntuacion))]} {max(max_puntuacion)}")
        max_puntuacion.remove(max(max_puntuacion))
else:
    print("No hay ganadores")

